title: TUS-REC
description: Website for the TUS-REC MICCAI Challenge.
theme: just-the-docs

url: https://github-pages.ucl.ac.uk/tus-rec-challenge/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/img2025/logo.png"


color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

search_enabled: false

back_to_top: true
back_to_top_text: "Back to top"

footer_content: Created by the TUS-REC Organisation Team.